=== AlexFielder/iLogicdotnet/iLogicdotnet/iLogicdotnet/iLogicRules.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="iLogicRule" type="iLogicRuleType" />
    <xs:complexType name="iLogicRuleType">
      <xs:sequence>
        <xs:element ref="Rule" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  <xs:element name="Rule" type="RuleType" />
  <xs:complexType name="RuleType">
      <xs:sequence>
        <xs:element ref="Name"/>
        <xs:element ref="IsActive"/>
        <xs:element ref="FireDependentImmediately"/>
        <xs:element ref="AutomaticOnParameterChange"/>
        <xs:element ref="Silentoperation"/>
        <xs:element ref="Text"/>
        <xs:element ref="ParentFileName"/>
      </xs:sequence>
  </xs:complexType>
  <xs:element type="xs:string"  name="ParentFileName"/>
  <xs:element type="xs:string" name="Name"/>
  <xs:element type="xs:boolean" name="IsActive"/>
  <xs:element type="xs:boolean" name="FireDependentImmediately"/>
  <xs:element type="xs:boolean" name="AutomaticOnParameterChange"/>
  <xs:element type="xs:boolean" name="Silentoperation"/>
  <xs:element type="xs:string" name="Text"/>
  
  </xs:schema>

=== AlexFielder/iLogicdotnet/iLogicdotnet/iLogicdotnet/iLogicRules.xml
<?xml version="1.0" encoding="utf-8" ?>
<iLogicRule xmlns:gruk="https://twitter.com/AlexFielder"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.w3schools.com/AlexFielder iLogicRules.xsd">
  <Rule>
    <Name>str1234</Name>
    <IsActive>true</IsActive>
    <FireDependentImmediately>true</FireDependentImmediately>
    <AutomaticOnParameterChange>true</AutomaticOnParameterChange>
    <Silentoperation>true</Silentoperation>
    <Text>str1234</Text>
    <ParentFileName>Filename</ParentFileName>
  </Rule>
  <Rule>
    <Name>str12345</Name>
    <IsActive>true</IsActive>
    <FireDependentImmediately>true</FireDependentImmediately>
    <AutomaticOnParameterChange>true</AutomaticOnParameterChange>
    <Silentoperation>true</Silentoperation>
    <Text>str1234</Text>
    <ParentFileName>Filename</ParentFileName>
  </Rule>
  <Rule>
    <Name>str12347</Name>
    <IsActive>true</IsActive>
    <FireDependentImmediately>true</FireDependentImmediately>
    <AutomaticOnParameterChange>true</AutomaticOnParameterChange>
    <Silentoperation>true</Silentoperation>
    <Text>str1234</Text>
    <ParentFileName>Filename</ParentFileName>
  </Rule>
  <Rule>
    <Name>string</Name>
    <IsActive>true</IsActive>
    <FireDependentImmediately>false</FireDependentImmediately>
    <AutomaticOnParameterChange>false</AutomaticOnParameterChange>
    <Silentoperation>false</Silentoperation>
    <Text>123af45</Text>
    <ParentFileName>filename</ParentFileName>
  </Rule>
</iLogicRule>
