=== AlexFielder/iLogicdotnet/iLogicdotnet/iLogicdotnet/InventorTreeStructs.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!--Here follows my description of a typical Inventor (Assembly) File tree-->
  <xs:element name="InventorTreeStruct" type="InventorTreeType" />
  <xs:complexType name="InventorTreeType">
    <xs:sequence>
      <xs:element ref="FileReference" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="FileReference" type="FileReferenceType" />
  <xs:complexType name="FileReferenceType">
    <xs:sequence>
      <xs:element name="FullFileName" />
      <xs:element name="Occurrence" type="InventorOccurrenceType" minOccurs="1" maxOccurs="unbounded" />
      <xs:element ref="Parameters" minOccurs="0" maxOccurs="unbounded" />
      <xs:element ref="FileType" maxOccurs ="1" />
      <xs:element name="IsSuppressed" type="xs:boolean" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="InventorOccurrenceType">
    <xs:sequence>
      <xs:element name="ParentFileName" />
      <xs:element name="OccurrenceLocalName" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name ="Parameters" type="InventorParameterCollectionType" />
  <xs:complexType name="InventorParameterCollectionType">
    <xs:sequence>
      <xs:element ref="Parameter" minOccurs ="0" maxOccurs ="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="Parameter" type="InventorParameterType" />
  <xs:complexType name="InventorParameterType">
    <xs:sequence>
      <xs:element name="ParameterName" />
      <xs:choice id ="ParameterValue" minOccurs="0" maxOccurs="1">
        <xs:element name="ParameterDoubleValue" type="xs:double" minOccurs="0" maxOccurs="1" />
        <xs:element name="ParameterBooleanValue" type="xs:boolean" minOccurs="0" maxOccurs="1" />
        <xs:element name="ParameterTextValue" type="xs:string" minOccurs="0" maxOccurs="1" />
      </xs:choice>
      <xs:element ref="LinkedParameter" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="LinkedParameter" type="InventorLinkedParameter" />
  <xs:complexType name="InventorLinkedParameter">
    <xs:sequence>
      <xs:element name="IsLinked" type="xs:boolean" />
      <xs:element name="LinkedFileName" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="FileType" type="InventorFileType" />
  <xs:complexType name="InventorFileType">
    <xs:sequence>
      <xs:element name="HasChildren" type="xs:boolean" nillable="false" />
      <xs:element name="FileExtension" type="xs:string" nillable="false " />
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== AlexFielder/iLogicdotnet/iLogicdotnet/iLogicdotnet/InventorTreeStructs.xml
<?xml version="1.0" encoding="utf-8" ?>
<InventorTreeStruct xmlns:gruk="https://twitter.com/AlexFielder"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.w3schools.com/AlexFielder InventorTreeStructs.xsd">
  <!--Here follows some example data build around the XSD file.-->
  <FileReference>
    <FullFileName>FileName001</FullFileName>
    <Occurrence>
      <ParentFileName>ParentAssembly</ParentFileName>
      <OccurrenceLocalName>BrowserNodeName</OccurrenceLocalName>
    </Occurrence>
    <Parameters>
      <Parameter>
        <ParameterName>Parameter001</ParameterName>
        <ParameterDoubleValue>0.001</ParameterDoubleValue>
        <!-- uncomment the following to prove the choice works!-->
        <!--<ParameterBooleanValue>true</ParameterBooleanValue>-->
        <!--<ParameterTextValue>Parameter001Value</ParameterTextValue>-->
        <LinkedParameter>
          <IsLinked>false</IsLinked>
          <LinkedFileName>C:\Some\path\to\a\linked\file.xls</LinkedFileName>
        </LinkedParameter>
      </Parameter>
      <Parameter>
        <ParameterName>Parameter002</ParameterName>
        <ParameterDoubleValue>0.001</ParameterDoubleValue>
        <LinkedParameter>
          <IsLinked>false</IsLinked>
          <LinkedFileName>C:\Some\path\to\another\linked\file.xls</LinkedFileName>
        </LinkedParameter>
      </Parameter>
    </Parameters>
    <FileType>
      <HasChildren>true</HasChildren>
      <FileExtension>.ipt</FileExtension>
    </FileType>
    <IsSuppressed>true</IsSuppressed>
  </FileReference>
  <FileReference>
    <FullFileName>FileName002</FullFileName>
    <Occurrence>
      <ParentFileName>ParentAssembly</ParentFileName>
      <OccurrenceLocalName>BrowserNodeName</OccurrenceLocalName>
    </Occurrence>
    <Parameters>
      <Parameter>
        <ParameterName>Parameter001</ParameterName>
        <ParameterDoubleValue>0.001</ParameterDoubleValue>
        <!-- uncomment the following to prove the choice works!-->
        <!--<ParameterBooleanValue>true</ParameterBooleanValue>-->
        <!--<ParameterTextValue>Parameter001Value</ParameterTextValue>-->
        <LinkedParameter>
          <IsLinked>false</IsLinked>
          <LinkedFileName>C:\Some\path\to\a\linked\file.xls</LinkedFileName>
        </LinkedParameter>
      </Parameter>
      <Parameter>
        <ParameterName>Parameter002</ParameterName>
        <ParameterDoubleValue>0.001</ParameterDoubleValue>
        <LinkedParameter>
          <IsLinked>false</IsLinked>
          <LinkedFileName>C:\Some\path\to\another\linked\file.xls</LinkedFileName>
        </LinkedParameter>
      </Parameter>
    </Parameters>
    <FileType>
      <HasChildren>true</HasChildren>
      <FileExtension>.ipt</FileExtension>
    </FileType>
    <IsSuppressed>false</IsSuppressed>
  </FileReference>
</InventorTreeStruct>
